#!/bin/bash

source "$XDG_CONFIG_HOME/cheat/lib/parsing.sh"
source "$XDG_CONFIG_HOME/cheat/lib/read_input.sh"

NOTE_DIR="$XDG_CONFIG_HOME/cheat/cheatsheets/community/"

fuzzy_find="false"

while getopts "f" opt; do
    case $opt in
        f)
            fuzzy_find="true"
            ;;
        \?)
            echo "Invalid option"
            exit 1
            ;;
    esac
done

shift $((OPTIND - 1))

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

if [[ "$fuzzy_find" == "true" ]]; then
    note_path=$(fdfind . "$XDG_CONFIG_HOME/cheat/cheatsheets/" | sed -E 's#^.*(personal|community)/?(.*)$#\2#' | grep '.'|grep '/' | fzf)

else
    query=$(read_input $1)
    eval $(get_parts $query)
    note_path="$base_topic/$sub_topic"
fi
if ! cheat "$note_path" > "$tmp" 2> /dev/null; then
    #TODO write to tmp dir?
    if ! curl -s "cht.sh/$query" -o "$tmp"; then
        echo "failed to fetch data"
        exit 1
    fi
    # clean input
    sed -i 's/\x1b\[[0-9;]*m//g' "$tmp"

    is_ok=$(is_response_ok "$tmp")
    case "$is_ok" in
        "invalid") echo "not a valid cheat sheet"; exit 0
            ;;
        "unknown") cat "$tmp"; exit 0
            ;;
    esac

        # TODO - only make if it doesnt exist
        dir="$NOTE_DIR/$base_topic"  
        abs_file_path="$dir/$sub_topic"
        mkdir -p "$dir"  
        if [[ ! -f $abs_file_path ]]; then
            cp "$tmp" "$abs_file_path"
            echo "saved to dir: $note_path"
        fi
fi

batcat -l markdown --paging always --file-name "$note_path" "$tmp"
#tmux neww bash -c "curl -s cht.sh/$query  | batcat -l markdown -p --paging never & while [ : ]; do sleep 1; done"
